FROM python:3.8-slim


# Install and update 
RUN apt-get update -y && \
    apt-get upgrade -y && \
    /usr/local/bin/python -m pip install --upgrade pip


#ENV /app /app
WORKDIR /work
COPY ./requirements.txt /work
COPY ./secret.json /work

# Install production dependencies.
RUN pip install -r requirements.txt

COPY . /work
EXPOSE 80


CMD uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
