version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0
  cloudrun: circleci/gcp-cloud-run@1.0.2

jobs:
    build_deploy:
      docker:
        - image: circleci/python:3.8
      steps:
        - checkout
        - setup_remote_docker:
            version: 19.03.13
            docker_layer_caching: true
        - run:
            name: Build app binary and Docker image
            command: |
              echo 'export PATH=$PATH:/.local/bin' >> $BASH_ENV
              echo ${GCP_PROJECT_KEY} | base64 -d -i > $HOME/gcloud-service-key.json
              echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV
              echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
              echo 'export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV && source $BASH_ENV
              docker build -t us-east1-docker.pkg.dev/$GOOGLE_PROJECT_ID/$SERVICE_NAME/$IMAGE_NAME -t us-east1-docker.pkg.dev/$GOOGLE_PROJECT_ID/$SERVICE_NAME/$IMAGE_NAME:$TAG .
        - gcp-gcr/gcr-auth:
            gcloud-service-key: GOOGLE_CLOUD_KEYS
            google-project-id: GOOGLE_PROJECT_ID
            google-compute-zone: GOOGLE_COMPUTE_ZONE
        - run:
            name: push to artefact repository
            command: |
              gcloud auth configure-docker us-east1-docker.pkg.dev
              docker push us-east1-docker.pkg.dev/$GOOGLE_PROJECT_ID/$SERVICE_NAME/$IMAGE_NAME
        - cloudrun/deploy:
            image: us-east1-docker.pkg.dev/$GOOGLE_PROJECT_ID/$SERVICE_NAME/$IMAGE_NAME:$TAG
            platform: managed
            region: us-east1
            service-name: $SERVICE_NAME
            unauthenticated: true
# Invoke jobs via workflows
workflows:
  build_deploy_gcp:
    jobs:
      - build_deploy